name: Build Gradle project

on: [push, pull_request]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle
      run: gradle build
    - name: Run test with Gradle
      run: gradle build